### ISSUE TITLE
[Feature] Add option to download with server timestamp

### ISSUE THREAD

**Issue by ZorinFoss** [BeanVortex/BitKip#17]
Hi @BeanVortex ,

Please add option to download with server timestamp. This option exist in aria and it will be good to add it to `BitKip`.

![aria](https://github.com/BeanVortex/BitKip/assets/132728893/fc2daeaf-8614-4c57-89aa-3a6973419329)

Thanks,

**Comment by BeanVortex** [comment]
I appreciate your suggestion, and I’ll consider implementing it in future updates.

**Comment by BeanVortex** [comment]
check this out: 
https://github.com/BeanVortex/BitKip/releases/tag/v1.4.9
